updateDocsComment: >
  Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would update some of our documentation based on your changes.
requestInfoReplyComment: >
  We would appreciate it if you could provide us with more info about this issue/pr!
requestInfoLabelToAdd: request-more-info

newPRWelcomeComment: >
  Thanks so much for opening your first PR here!
firstPRMergeComment: >
  Congrats on merging your first pull request here! :tada: How awesome!
  
newIssueWelcomeComment: >
  Thanks for opening this issue, a maintainer will get back to you shortly!
  
# *OPTIONAL* default titles to check against for lack of descriptiveness
# MUST BE ALL LOWERCASE
requestInfoDefaultTitles:
  - update readme.md
  - updates
  - minor fixes
